# Generated by Django 3.2.8 on 2021-12-10 06:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('has_started', models.BooleanField(default=False)),
                ('is_notallowed', models.BooleanField(default=True)),
                ('StartTime', models.DateTimeField(blank=True, null=True)),
                ('ExpLgtTime', models.DateTimeField(blank=True, null=True)),
                ('CompTime', models.DateTimeField(blank=True, null=True)),
                ('Timetaken', models.DateTimeField(blank=True, default=0, null=True)),
                ('score', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
