# Generated by Django 3.2.8 on 2021-12-10 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_profile_timetaken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='Timetaken',
            field=models.TextField(blank=True, null=True),
        ),
    ]
