# Generated by Django 3.2.8 on 2021-12-31 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_profile_timetaken'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='zone',
            field=models.CharField(default='None', max_length=100),
        ),
    ]
