# Generated by Django 3.2.8 on 2022-01-04 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_profile_zone'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='zone_activate',
            field=models.BooleanField(default=False),
        ),
    ]
