# Generated by Django 3.2.8 on 2022-01-06 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_profile_zone_activate'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='riddle_activate',
            field=models.BooleanField(default=False),
        ),
    ]
