# Generated by Django 3.2.9 on 2022-02-27 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_profile_riddle_activate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='zone',
            field=models.CharField(default='Red', max_length=100),
        ),
    ]
