# Generated by Django 3.2.8 on 2022-01-08 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_question_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='riddle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('riddle', models.CharField(max_length=500)),
                ('riddledesc', models.TextField(blank=True, null=True)),
                ('answer', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='question',
            name='type',
        ),
    ]
