# Generated by Django 4.0.2 on 2022-04-12 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_auto_20220108_1842'),
        ('quiz', '0003_auto_20220108_1842 2'),
    ]

    operations = [
    ]
